### PR TITLE
Update clusterFunctionsLSF.R

### PR DESCRIPTION
**Pull request by phaverty**

### CODE REVIEW

**Comment by mllg** [comment]
I don't have access to an LSF system at the moment... Is this all you had to change to get LSF running?

**Comment by phaverty** [comment]
I'm not quite there yet.  Job submission "works" now, but the jobs fail
immediately because they can't find a temp directory that doesn't exist.
Also, job arrays don't seem to work. I'm doing

resources=list(queue="long", walltime=1440, n.cores=1, memoryGb=5,
chunks.as.arrayjobs=TRUE, n.chunks=500)

but I am getting 1 chunk per job.  Do chunks.as.array.jobs and n.chunks go
in resources? I didn't see them in the formal args of any function, but I
thought they used to be function arguments rather than going in this list.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
I figured out where n.cores goes (in chunkIds).

**Comment by mllg** [comment]
> I'm not quite there yet.  Job submission "works" now, but the jobs fail
> immediately because they can't find a temp directory that doesn't exist.

Do you have the same problem if you submit without batchtools? Anything special in your job file? If you need a unique identifier (e.g., to create an extra temp folder), you can use the variable `job.hash` in the template.

Note that there is a debug mode implemented in batchtools (using [debugme](https://github.com/gaborcsardi/debugme/)). Load the package with:
```r
Sys.setenv(DEBUGME="batchtools"); library(batchtools)
```
You will get some extra output. Additionally, the brewed templates will be stored in `[file.dir]/jobs/[job.hash].job`. Check them carefully that everything looks right. If no need more assistance, please post your template and config file.

> Also, job arrays don't seem to work. I'm doing
> resources=list(queue="long", walltime=1440, n.cores=1, memoryGb=5,
> chunks.as.arrayjobs=TRUE, n.chunks=500)
> 
> but I am getting 1 chunk per job.  Do chunks.as.array.jobs and n.chunks go
> in resources? I didn't see them in the formal args of any function, but I
> thought they used to be function arguments rather than going in this list.

You got it. Pass the chunked ids to submitJobs and set the resource `chunks.as.arrayjobs`. This part isn't very well document yet, I'll add some examples to the documentation of `submitJobs`.

**Comment by mllg** [comment]
I've merged this one for now. Are you making progress?

**Comment by phaverty** [comment]
Great, thanks.  I'm sure those two changes are correct. I'm experimenting
with piping brew output through bsub to avoid one of the temp files. I had
to fall back to BatchJobs to my current task finished (but I'm having
SQLite trouble. Our NFS setup has some nasty latency.)

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Pull request merged**
