### PR TITLE
max.concurrent.jobs for array jobs

### PR DESCRIPTION
**Pull request by mnwright**
If `chunks.as.arrayjobs = TRUE` and `max.concurrent.jobs` is used, it should be based on jobs not chunks. 

Do we need a switch for `chunks.as.arrayjobs = FALSE`?

### CODE REVIEW

**Comment by mllg** [comment]
Yes, there must be a switch for `chunks.as.arrayjobs`. I've pushed a fix for this. Can you confirm that this works for you?

**Comment by mnwright** [comment]
Almost. `*` has higher precedence than `!`.

**Comment by mllg** [comment]
Ouch, right. Thanks. That was the precedence of C :cry:

**Comment by mnwright** [comment]
Thanks!

**Pull request merged**
